const mongoose=require("mongoose")

const order=mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        country:{
            type:String,
            requiredd:true
        },
        state:{
            type:String,
            requiredd:true
        },
        city:{
            type:String,
            requiredd:true
        },
        pincode:{
            type:Number,
            requiredd:true
        },
        mobile:{
            type:Number,
            required:true
        }
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            quantity:{
                type:Number,
                required:true,
                default:1
            },
            images:{
                type:String,
                required:true
            },
            price:{
                type:String,
                required:true
            },
            product:{
               type:mongoose.Schema.ObjectId,
               ref:"Product",
               required:true 
            }
        }
    ],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"User",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            // required:true
        },
        status:{
            type:String,
            // required:true
        }
    },
    paidAt:{
        type:Date,
        // required:true
    },
    itemsPrice:{
        type:Number,
        default:0
    },
    taxPrice:{
        type:Number,
        default:0
    },
    shippingPrice:{
        type:Number,
        default:0
    },
    totalPrice:{
        type:Number,
        default:0
    },
    orderStatus:{
        type:String,
        required:true,
        default:"processing.."
    },
    deliveredAt:Date,
    createdAt:{
        type:Date,
        default:Date.now()
    }
    
})

module.exports=new mongoose.model("Order",order)